import { Link } from "react-router-dom";

const Determinance = () =>{
    return (
        <div className="scroll-pl-6 snap-x ... p-24 m-8 ">
           <p className=" text-2x1 text-base italic font-bold mb-7">Step #1: Determine Your Starting Point</p> 
           <iframe width="700" height="315" src="https://www.youtube.com/embed/K1xYlsfSoqY?si=UahiR7stNCdXqKby" 
           title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
           referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
           <h1 className="text-2xl mb-5 font-bold mt-7">As Coach Staci lays out in the video above, we need to answer a few key questions when designing a workout: <br />
            </h1>
            <h1 className="text-2xl mb-5 font-bold mt-7">QUESTION 1: What are your goals?...▼ <br />
            </h1>
            <p className=" text-2x1 text-base italic font-bold mb-7"> ◙ Are you trying to lose weight? Awesome.</p> 
            <p className=" text-2x1 text-base italic font-bold mb-7"> ◙ Are you trying to bulk up or build muscle? Great.</p> 
            <p className=" text-2x1 text-base italic font-bold mb-7"> ◙ Are you preparing for your first 5k? Swell.</p> 

            <h1 className="text-2xl mb-5 font-semiblond mt-7">Whatever your goals are, it’s good to write them down and be aware of what you’re trying to accomplish.  <br />
            </h1>
            <h1 className="text-2xl mb-5 font-semiblond mt-7"> These goals will shape HOW you build your workout.<br />
            </h1>
            <h1 className="text-2xl mb-5 font-semiblond mt-7"> <b>An effective way to create goals is by using the SMART method,</b>which stands for <b>specific</b>, <b>measurable</b>, <b>attainable</b>, <b>relevant</b>, and <b>timely</b>.[1]<br />
            </h1>

            <h1 className="text-2xl mb-5 font-semiblond mt-7"> <b>⦿ Specific </b>-- Specifically state what is to be accomplished-- For example, “I want to gain 5 pounds of muscle.” (In this article we’ll cover how to build a workout to help you lose weight, build muscle, and get stronger. If you have specific goals like getting your first pull-up, getting your first push-up, or running your first 5k, we have articles covering each of these in detail.) <br />
            </h1>
            <h1 className="text-2xl mb-5 font-semiblond mt-7"> <b>⦿ Measurable </b>– Find a way to measure your progress.  For example, you will need body composition equipment to assess your fat and muscle mass.<br />
            </h1>
            <h1 className="text-2xl mb-5 font-semiblond mt-7"><b>⦿ Attainable</b>– Your goals should be realistically attainable. For example, a realistic rate of muscle gain is up to 0.5 pounds per week. To gain 5 pounds of muscle, 10 weeks would be an attainable starting point. <br />
            </h1>
            <h1 className="text-2xl mb-5 font-semiblond mt-7"> <b> ⦿ Relevant</b>– Your goals must relate to your interests, needs, likes/dislikes, and abilities.  Another thing to remember is that your goals need to be generated by you and you alone! For example, if you don’t care about gaining 5 pounds of muscle, or aren’t quite sure how this will benefit your life, then this isn’t a great goal for you! <br />
            </h1>
            <h1 className="text-2xl mb-5 font-semiblond mt-7"> <b> ⦿ Timely</b>– Your goals must have a timeline for completion.  If your goal is to gain 5 pounds of muscle then a reasonable end-point should be at minimum 10 weeks. <br />
            </h1>
            <h1 className="text-2xl mb-5 font-semiblond mt-7">If you are struggling with your goals, revisit the SMART framework and see if you can tweak your goals to work better for you.<br />
            </h1> 
            <h1 className="text-2xl mb-5 font-bold mt-7">QUESTION 2:How much time can you devote to exercise?.. ▼ <br />
            </h1>
            <p className=" text-2x1 text-base italic font-semibold mb-7">If you can do an hour a day, that’s fantastic. .</p> 
            <p className=" text-2x1 text-base italic font-semibold mb-7">But maybe you have a wife or husband, three kids, a dog, two jobs, and no robot butler….</p> 
                <img src="src\assets\sponge-bob-is-busy.webp" alt="" />
                <p className=" text-2x1 text-base italic font-semibold mb-7">…then maybe you only have thirty minutes, twice a week.</p>.
                <p className=" text-2x1 text-base italic font-semibold mb-7"><b>That’s fine too!</b></p>.
                <h1 className="text-2xl mb-5 font-semiblond mt-7">In the past 15 years of working with folks from all walks of life, we’ve realized there’s a warped sense of HOW much working out is needed to achieve your goals. For many of our 1-on-1 coaching clients, working out 2 to 4 times per week for 30 to 45 minutes is PLENTY to see some serious progress. (And as Staci mentioned in the video above, even 1 workout per week can work, especially for beginners!)<br />
            </h1>
            <h1 className="text-2xl mb-5 font-bold mt-7"><b>Another key thing to remember: your workout doesn’t have to happen all at once!</b>According to the American College of Sports Medicine (ACSM), if you accumulate three 10-minute bouts of exercise throughout the day to total 30 minutes of exercise, then that is as effective as someone who does one 30-minute bout of exercise<br />
            </h1>
            <h1 className="text-2xl mb-5 font-bold mt-7">Now, no matter how much time you have, developing the most efficient workout is crucial.<br />
            </h1>
            <p className=" text-2x1 text-base italic font-semibold mb-7">Why spend two hours in a gym when you can get just as much accomplished in 30 minutes, right?</p>.
            <p className=" text-2x1 text-base italic font-semibold mb-7"><b>Here’s the good news:</b> weight training is the fat-burning prize fight victor, and efficiency rules all</p>.
            <img src="src\assets\barbell-press.webp" alt="" />
            <h1 className="text-2xl mb-5 font-bold mt-7">So whether you are building muscle or looking to lose weight, a strength training workout will get you the results you’re after (when combined with the right eating strategy!)<br />
            </h1>
            <h1 className="text-2xl mb-5 font-bold mt-7">While we’re talking about time, let me quickly mention something important:<br />
            </h1>
            <p className=" text-2x1 text-base italic font-semibold mb-7">Proper expectations!</p>.
            <h1 className="text-2xl mb-5 font-bold mt-7"><b>As we cover “How Fast Can I Get the Body I Want,” make sure you are thinking about your journey with a realistic timeline:</b><br />
            </h1>

            <iframe width="560" height="315" src="https://www.youtube.com/embed/ieY_8ZL0v78?si=xa3F1tnn9gYqTdR1" 
            title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
             referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
             <h1 className="text-2xl mb-5 font-bold mt-7"><b>As we mention in that guide, here are some realistic timeframes for weight loss or muscle gain:</b></h1>
             <p className="text-lg mb-3 text-orange-500">For weight loss, a realistic rate is 0.5-1% of body weight per week. For example, if you weigh 200 pounds with a weight loss goal of 0.5% per week, your goal would be a 500-calorie-per-day deficit.</p>
             <p className="text-lg mb-3 text-orange-500">For muscle gain, a realistic rate is 0.25-0.5% of body weight per week. For example, if you weigh 200 pounds with a muscle gain goal of 0.25% per week, your goal would be a 250-calorie-per-day surplus</p>
             <h1 className="text-2xl mb-5 font-bold mt-7">QUESTION 3:WHERE do you want to work out?.. ▼ <br /> </h1>
             <p className="text-lg mb-3 text-green-500">Where you work out will largely determine if you are going to train with your body’s weight, or if you can start doing gym strength training</p>
             <p className="text-lg mb-3 text-green-500">If you’re paying attention here, you may notice I’m setting you up to work out no matter what your current situation is.</p>
            <p className="text-2x1 text-base italic font-semibold mb-7">Why?</p>
            <p className="text-lg mb-3 text-green-500">Because according to ACSM, the #1 reason people don’t exercise is</p>
            <p className="text-2x1 text-base italic font-bold mb-7 text-orange-600">They don’t have time for it.</p>
             <img src="src\assets\late.gif" alt="" />
             <p className="text-lg mb-3 text-green-500 italic font- text-center">All of us, all the time.</p>
             <h1 className="text-2xl mb-5 font-bold mt-7 text-yellow-600">BUT, with the information I’m hitting you with, technically you should have no excuse for not exercising unless (you’re injured or sick)</h1>
             <p className="text-2x1 text-base italic font-bold mb-7">After all, your workout:....▼ <br />
             <b className="italic">⁍ Can be accumulated with just 10-minute bouts of exercise throughout the day <br /></b>
             <b className="italic">⁍ Doesn’t need to be done with a gym membership <br /></b>
             <b className="italic">⁍ Can be done with exercises in the comfort of your own home or while outside (weather permitting).</b>
             </p>
        </div>
    );
  }
  
  export default Determinance